---

hostname: ce-acme1
domain_name: emea.com

celoopback:
  address: 172.1.0.111
  mask: 255.255.255.255


interfaces:


  0/1.100:
    alias: connection pe-dublin
    vlan: 100
    address: 192.168.100.2
    mask: 255.255.255.252


bgp:
  asn: 65111
  neighbor:
    - {address: 192.168.100.1, remote_as: 1}
