---

hostname: pe-paris
domain_name: emea.com

peloopback:
  address: 10.255.0.4
  mask: 255.255.255.255


customers:
  acme:
    rd: 10.255.0.4:10
    rt: "10:10"

  corpnet:
    rd: 10.255.0.4:20
    rt: "10:20"

  banco:
    rd: 10.255.0.4:30
    rt: "10:30"  


  metrolink:
    rd: 10.255.0.4:40
    rt: "10:40"  


interfaces:
  0/1.34:
    alias: connection p1
    vlan: 34
    address: 10.0.254.1
    mask: 255.255.255.252

  0/1.200:
    alias: connection ce-banco
    vlan: 200
    address: 192.168.200.1
    mask: 255.255.255.252
    intvrf: banco

ospf:
   proc: 1
   ldp: mpls ldp autoconfig
   networks:
    - {network: 0.0.0.0, mask: 255.255.255.255, area: 0}


bgp:
  asn: 1
  neighbor:
    - {address: 10.255.0.100, remote_as: 1}
    - {address: 10.255.0.200, remote_as: 1}

  ups:
    - {address: 10.255.0.100, loopback: Loopback0}
    - {address: 10.255.0.200, loopback: Loopback0}

  ipv4: 
    - {ce: 192.168.200.2, remote_as: 65113, cvrf: banco}

  vpnv4:
    - {address: 10.255.0.100, remote_as: 1}
    - {address: 10.255.0.200, remote_as: 1}



policy:
  outbound:
    - {ce: 192.168.200.2, asover: as-override}

